# Generated by Django 4.0.3 on 2022-03-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoDoacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_agendamento', models.DateTimeField()),
                ('des_destinatario', models.CharField(max_length=100)),
                ('dat_criacao', models.DateTimeField(auto_now=True)),
                ('dat_atualizacao', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.TextField(max_length=300)),
            ],
            options={
                'ordering': ['-dat_atualizacao'],
            },
        ),
    ]
